version = 0.1

[default.deploy.parameters]
stack_name = "spam-guard"
resolve_s3 = true
s3_prefix = "spam-guard"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
